"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "./components/landing/Footer";
import Header from "./components/landing/Header";
import { CartProvider } from "./contexts/CartContext";
import CookieBanner from "./components/ui/CookieBanner";
import { frFR } from "@clerk/localizations/fr-FR";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Si tu veux réactiver le SEO plus tard, dé-commente ceci:
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider localization={frFR}>
      <CartProvider>
        <html lang="fr" data-theme="emerald">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Header />
            {children}
            <Footer />
            <CookieBanner />
          </body>
        </html>
      </CartProvider>
    </ClerkProvider>
  );
}