"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import Header from "./components/Header";
import { CartContext, CartItem, CartContextType } from "./contexts/CartContext";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Si tu veux réactiver le SEO plus tard, dé-commente ceci:
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const [cart, setCart] = useState<CartItem[]>([]);
  const value: CartContextType = { cart, setCart };

  return (
    <ClerkProvider>
      <CartContext.Provider value={value}>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Header />
            {children}
          </body>
        </html>
      </CartContext.Provider>
    </ClerkProvider>
  );
}
